name: default
label: Default
extends: uesio/io.default
definition:
  uesio.styleTokens:
    root:
      - lg:grid-cols-[minmax(80px,auto)_308px_minmax(auto,940px)_minmax(80px,auto)]
      - md:grid-cols-none
    header:
      - lg:col-span-4
      - md:col-span-1
      - sticky
      - top-0
      - border-b-1
      - border-slate-200
      - z-20
    content:
      - lg:col-start-3
      - lg:col-end-3
      - lg:row-start-2
      - md:col-start-1
      - md:col-end-1
      - md:row-start-3
      - lg:p-0
      - lg:pt-8
      - md:p-10
      - p-6
    left:
      - lg:col-start-2
      - lg:col-end-2
      - lg:h-[calc(100vh_-_180px)]
      - lg:sticky
      - lg:top-[134px]
      - lg:mr-12
      - lg:border-b-2
      - lg:border-slate-800
      - lg:border-r-2
      - lg:border-t-1
      - lg:border-l-1
      - lg:rounded
      - md:h-auto
      - md:col-start-1
      - md:col-end-1
      - sticky
      - top-[87px]
      - bg-white/90
      - backdrop-blur
      - z-20
public: true
